### ISSUE TITLE
Error message at startup

### ISSUE THREAD

**Issue by nova76** [Fiware/tutorials.Media-Streams#7]
I received the following error message at startup. What can I do?

...
Digest: sha256:a50aae18b6d329b5e2e22317d7cc2c07c72608889aa1b1c87269b8ab12179e39
Status: Downloaded newer image for fiware/stream-oriented-kurento:6.8.0
 ---> f999e2a2f60c
Step 2/3 : RUN  echo "deb http://ubuntu.kurento.org/ trusty kms6" | tee /etc/apt/sources.list.d/kurento.list    && wget -O - http://ubuntu.kuren      to.org/kurento.gpg.key | apt-key add -  && apt-get update     && apt-get -y install kms-pointerdetector-6.0     && apt-get -y install kms-crowdd      etector-6.0     && apt-get -y install kms-platedetector-6.0     && apt-get -y install kms-chroma-6.0    && apt-get clean     && rm -rf /var/lib/      apt/lists/*
 ---> Running in 575fb155fdac
deb http://ubuntu.kurento.org/ trusty kms6
--2020-06-03 11:34:17--  http://ubuntu.kurento.org/kurento.gpg.key
Resolving ubuntu.kurento.org (ubuntu.kurento.org)... 52.218.100.164
Connecting to ubuntu.kurento.org (ubuntu.kurento.org)|52.218.100.164|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-03 11:34:18 ERROR 404: Not Found.

gpg: no valid OpenPGP data found.
The command '/bin/sh -c echo "deb http://ubuntu.kurento.org/ trusty kms6" | tee /etc/apt/sources.list.d/kurento.list    && wget -O - http://ubun      tu.kurento.org/kurento.gpg.key | apt-key add -  && apt-get update     && apt-get -y install kms-pointerdetector-6.0     && apt-get -y install km      s-crowddetector-6.0     && apt-get -y install kms-platedetector-6.0     && apt-get -y install kms-chroma-6.0    && apt-get clean     && rm -rf /      var/lib/apt/lists/*' returned a non-zero code: 2

**Comment by jason-fox** [comment]
This appears to be an issue with the kurento servers - Maybe they have updated their configuration. I'll try to investigate.

**Comment by dpatil-fw** [comment]
I faced the same issue as above. The links are broken.

Looks like trusty is no longer supported, please check this: 
https://doc-kurento.readthedocs.io/en/6.10.0/project/relnotes/v6_10_0.html#bye-ubuntu-trusty

The Dockerfile in the project will need to be replaced with the latest one:
https://github.com/Kurento/kurento-docker/blob/master/kurento-media-server/Dockerfile

And UBUNTU_CODENAME will need to be replaced with either xenial or bionic

I tried it, so far no issues in installation. I am yet to try the other steps in this tutorial.
