### ISSUE TITLE
Can't clone repo - kurento-examples folder is empty

### ISSUE THREAD

**Issue by starlessboi** [Fiware/tutorials.Media-Streams#8]
HI
just tried to clone the repo, it clones successfully, but sub folders of kurento-examples is empty,
I think it's because of spaces in folder names, How can I clone that?
thanks

**Comment by jason-fox** [comment]
Can you re-run the `git submodule update --init --recursive` command as stated in the `README`:

```console
git clone https://github.com/FIWARE/tutorials.Media-Streams.git
cd tutorials.Media-Streams
git checkout NGSI-v2
git submodule update --init --recursive
```
